### ISSUE TITLE
Torrent search function not working -404 error

### ISSUE THREAD

**Issue by WolfganP** [Bartuzen/qBitController#132]
### Bug description

When using the torrent search function (so the metasearch execute in the sites via search plugins), any query I entered promptly returns an `**API returned an error 404**`
I made sure it does work via the webUI, QB v4.6.3

### Logs

No relevant error message in the Execution Log. Can't post it as I couldn't find any way to export it.

### qBitController version

0.8.5

### qBittorrent version

4.6.3

### Android version

13

**Comment by Bartuzen** [comment]
This is a weird issue and I can't replicate it. I'll have to check qBittorrent's source code.

**Comment by WolfganP** [comment]
> This is a weird issue and I can't replicate it. I'll have to check qBittorrent's source code.

Thx. Any way I can help? (qb logs don't seem to reflect anything related to webapi activity)

**Comment by Bartuzen** [comment]
I forgot to update here, but I checked the search start and result methods of qBittorrent. I found out that the search result method throws a 404 error if the search isn't found. But this shouldn't happen because the search ID that the search start method returns is immediately used for results. I'm really clueless on this one.

**Comment by Bartuzen** [comment]
Closing this issue because it's inactive and I can't reproduce it.
